ALTER SESSION SET CURRENT_SCHEMA = fly_the_end12B;


-------------------------------------------------------------------
-- TEST LOST UPDATE
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET AUTOCOMMIT OFF;
SET AUTOCOMMIT ON;
COMMIT;

SELECT trangthai FROM CT_DATVE 
WHERE MACT_DATVE = 'CTDV05211';


SELECT * FROM BAOCAOTHANG
WHERE THANG = 6 AND NAM = 2024
AND MACHUYENBAY = 'CB052';

EXECUTE UPDATE_TICKET_STATUS('CTDV05210', 2);
EXECUTE UPDATE_TICKET_STATUS('CTDV05211', 2);


-------------------------------------------------------------------
-- TEST NON-REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET AUTOCOMMIT OFF;
SET AUTOCOMMIT ON;
COMMIT;

SELECT *
FROM BAOCAOTHANG 
WHERE Thang = 6  
AND Nam = 2024;


SELECT * FROM CT_DATVE 
     JOIN VE
     ON VE.mAvE = CT_DATVE.MAVE
WHERE EXTRACT(YEAR FROM NGAYTHANHTOAN) = 2024 AND EXTRACT(MONTH FROM NGAYTHANHTOAN) = 6;

-------------------------------------------------------------------
-- TEST PHANTOM READ
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET AUTOCOMMIT OFF;
SET AUTOCOMMIT ON;
COMMIT;

SELECT *
FROM BAOCAOTHANG 
WHERE Thang = 6  
AND Nam = 2024;

SELECT * FROM CHUYENBAY WHERE MACHUYENBAY = 'CB022';
-------------------------------------------------------------------
-- TEST DEADLOCK
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET AUTOCOMMIT OFF;
SET AUTOCOMMIT ON;
COMMIT;

update hangve
set trangthai = 0
where mahangve
='HV001';

update hangve
set trangthai = 0
where mahangve
='HV002';